<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\ProfileWorker;

class ProfileWorkerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $arrayProfiles = [
            [
                'name' => 'Coordenador da Campanha',
                'scope' => 'campaign',
                'management' => 'GEZOON',
                'is_pre_campaign' => 0,
                'is_multiple' => false,
                'is_rural' => false,
                'is_pre_load' => false,
                'is_supervisor' => false,
            ],
            [
                'name' => 'Coordenador da Campanha Auxiliar',
                'scope' => 'campaign',
                'management' => 'GEZOON',
                'is_pre_campaign' => 0,
                'is_multiple' => false,
                'is_rural' => false,
                'is_pre_load' => false,
                'is_supervisor' => false,
            ],
            [
                'name' => 'Assistente Social',
                'scope' => 'cycle',
                'management' => 'GEZOON',
                'is_pre_campaign' => 0,
                'is_multiple' => false,
                'is_rural' => false,
                'is_pre_load' => false,
                'is_supervisor' => false,
            ],
            [
                'name' => 'Coordenador de Material',
                'scope' => 'cycle',
                'management' => 'Rede de Frio',
                'is_pre_campaign' => 1,
                'is_multiple' => false,
                'is_rural' => false,
                'is_pre_load' => false,
                'is_supervisor' => false,
            ],
            [
                'name' => 'Enfermeiro',
                'scope' => 'cycle',
                'management' => 'Rede de Frio',
                'is_pre_campaign' => 1,
                'is_multiple' => false,
                'is_rural' => false,
                'is_pre_load' => false,
                'is_supervisor' => false,
            ],
            [
                'name' => 'Motorista',
                'scope' => 'cycle',
                'management' => 'Rede de Frio',
                'is_pre_campaign' => 0,
                'is_multiple' => true,
                'is_rural' => false,
                'is_pre_load' => false,
                'is_supervisor' => false,
            ],
            [
                'name' => 'Equipe de Apoio',
                'scope' => 'cycle',
                'management' => 'Rede de Frio',
                'is_pre_campaign' => 1,
                'is_multiple' => true,
                'is_rural' => false,
                'is_pre_load' => false,
                'is_supervisor' => false,
            ],
            [
                'name' => 'Equipe de Apoio',
                'scope' => 'cycle',
                'management' => 'GEZOON',
                'is_pre_campaign' => 1,
                'is_multiple' => true,
                'is_rural' => false,
                'is_pre_load' => false,
                'is_supervisor' => false,
            ],
            [
                'name' => 'Equipe de Apoio',
                'scope' => 'cycle',
                'management' => 'GETRANS',
                'is_pre_campaign' => 1,
                'is_multiple' => true,
                'is_rural' => false,
                'is_pre_load' => false,
                'is_supervisor' => false,
            ],
            [
                'name' => 'Coordenador de Estatística',
                'scope' => 'cycle',
                'management' => 'GEZOON',
                'is_pre_campaign' => 0,
                'is_multiple' => false,
                'is_rural' => false,
                'is_pre_load' => false,
                'is_supervisor' => false,
            ],
            [
                'name' => 'Equipe de Estatística',
                'scope' => 'cycle',
                'management' => 'GEZOON',
                'is_pre_campaign' => 0,
                'is_multiple' => true,
                'is_rural' => false,
                'is_pre_load' => false,
                'is_supervisor' => false,
            ],
            [
                'name' => 'Coordenador de PA',
                'scope' => 'support',
                'management' => 'GEZOON',
                'is_pre_campaign' => 0,
                'is_multiple' => false,
                'is_rural' => false,
                'is_pre_load' => false,
                'is_supervisor' => false,
            ],
            [
                'name' => 'Supervisor de PA',
                'scope' => 'support',
                'management' => 'GEZOON',
                'is_pre_campaign' => 0,
                'is_multiple' => true,
                'is_rural' => false,
                'is_pre_load' => false,
                'is_supervisor' => true,
            ],
            [
                'name' => 'Equipe de Apoio de PA',
                'scope' => 'support',
                'management' => 'GEZOON',
                'is_pre_campaign' => 1,
                'is_multiple' => true,
                'is_rural' => false,
                'is_pre_load' => false,
                'is_supervisor' => false,
            ],
            [
                'name' => 'Motorista de PA',
                'scope' => 'support',
                'management' => 'GEZOON',
                'is_pre_campaign' => 1,
                'is_multiple' => true,
                'is_rural' => false,
                'is_pre_load' => false,
                'is_supervisor' => false,
            ],
            [
                'name' => 'Vacinador Reserva',
                'scope' => 'support',
                'management' => 'GEZOON',
                'is_pre_campaign' => 0,
                'is_multiple' => true,
                'is_rural' => false,
                'is_pre_load' => false,
                'is_supervisor' => false,
            ],
            [
                'name' => 'Supervisores Rural',
                'scope' => 'support',
                'management' => 'GEZOON',
                'is_pre_campaign' => 0,
                'is_multiple' => true,
                'is_rural' => true,
                'is_pre_load' => false,
                'is_supervisor' => false,
            ],
            [
                'name' => 'Auxiliar Rural',
                'scope' => 'support',
                'management' => 'GEZOON',
                'is_pre_campaign' => 0,
                'is_multiple' => true,
                'is_rural' => true,
                'is_pre_load' => false,
                'is_supervisor' => false,
            ],
            [
                'name' => 'Vacinador Rural',
                'scope' => 'support',
                'management' => 'GEZOON',
                'is_pre_campaign' => 0,
                'is_multiple' => true,
                'is_rural' => true,
                'is_pre_load' => false,
                'is_supervisor' => false,
            ],
            [
                'name' => 'Motorista Rural',
                'scope' => 'support',
                'management' => 'GEZOON',
                'is_pre_campaign' => 0,
                'is_multiple' => true,
                'is_rural' => true,
                'is_pre_load' => false,
                'is_supervisor' => false,
            ],
            [
                'name' => 'Supervisor de Posto',
                'scope' => 'point',
                'management' => 'GEZOON',
                'is_pre_campaign' => 0,
                'is_multiple' => false,
                'is_rural' => false,
                'is_pre_load' => true,
                'is_supervisor' => false,
            ],
            [
                'name' => 'Vacinador de Posto',
                'scope' => 'point',
                'management' => 'GEZOON',
                'is_pre_campaign' => 0,
                'is_multiple' => true,
                'is_rural' => false,
                'is_pre_load' => false,
                'is_supervisor' => false,
            ],
            [
                'name' => 'Anotador de Posto',
                'scope' => 'point',
                'management' => 'GEZOON',
                'is_pre_campaign' => 0,
                'is_multiple' => true,
                'is_rural' => false,
                'is_pre_load' => false,
                'is_supervisor' => false,
            ],
        ];

        foreach ($arrayProfiles as $profile) {
            ProfileWorker::create($profile);
        }
    }
}
